services:
  - type: web
    name: PharmaFrontend
    env: static
    staticPublishPath: dist/inventario-medicamentos
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/inventario-medicamentos